tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "inverse-primary": "#adc6ff",
        "surface": "#f8f9ff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-container": "#a36700",
        "on-primary-fixed": "#001a42",
        "on-secondary-container": "#00714d",
        "surface-container-high": "#dce9ff",
        "surface-dim": "#cbdbf5",
        "primary": "#0058be",
        "surface-container-lowest": "#ffffff",
        "on-background": "#0b1c30",
        "on-primary-container": "#fefcff",
        "on-primary-fixed-variant": "#004395",
        "secondary-fixed-dim": "#4edea3",
        "surface-variant": "#d3e4fe",
        "tertiary": "#825100",
        "on-primary": "#ffffff",
        "secondary": "#006c49",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-highest": "#d3e4fe",
        "tertiary-fixed": "#ffddb8",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#727785",
        "on-tertiary": "#ffffff",
        "background": "#f8f9ff",
        "inverse-surface": "#213145",
        "primary-container": "#2170e4",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#6cf8bb",
        "surface-container": "#e5eeff",
        "outline-variant": "#c2c6d6",
        "secondary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed": "#2a1700",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary-fixed": "#002113",
        "on-error": "#ffffff",
        "surface-tint": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#424754"
      },
      "borderRadius": {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
      "spacing": {"base": "8px", "margin-mobile": "16px", "margin-desktop": "48px", "lg": "40px", "xl": "64px", "gutter": "24px", "xs": "4px", "sm": "12px", "md": "24px"},
      "fontFamily": {"headline-lg-mobile": ["Quicksand"], "display-lg": ["Quicksand"], "headline-lg": ["Quicksand"], "body-lg": ["Quicksand"], "body-md": ["Quicksand"], "label-lg": ["Quicksand"], "headline-md": ["Quicksand"], "label-sm": ["Quicksand"]},
      "fontSize": {"headline-lg-mobile": ["28px", {"lineHeight": "1.3", "fontWeight": "700"}], "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}], "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "700"}], "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "500"}], "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}], "label-lg": ["14px", {"lineHeight": "1.2", "fontWeight": "700"}], "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}], "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "600"}]}
    }
  }
}
